[package]
name = "ron_vm"
version = "0.1.0"
authors = ["Mario Sieg (KerboGames) <support@kerbogames.com>"]
edition = "2018"

[lib]
name = "ronin_runtime"
path = "src/lib.rs"

[[bin]]
name = "ronin_virtual_machine"
path = "src/bin.rs"

[features]
default = ["simd"]
simd = []
config_file = ["serde", "serde_json"]

[dependencies]
# Required:
bitflags = "1.2.1"  # For bitsflags

# Optional (only needed for some special features):
serde = { version = "1.0.116", features = ["derive"], optional = true }
serde_json = { version = "1.0.57", optional = true }