[package]
name = "corium_compiler"
version = "0.1.0"
edition = "2018"
authors = ["Mario Sieg aka pinsrq <mt3000@gmx.de>"]

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = "0.19.6"
regex = "1"
